# Generated by Django 5.1.1 on 2024-09-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='package/images/')),
                ('hotel_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('day', models.SmallIntegerField()),
                ('person', models.SmallIntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
