# Generated by Django 5.1.1 on 2024-10-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('data_time', models.DateTimeField()),
                ('destination', models.CharField(max_length=100)),
                ('persons', models.CharField(choices=[('Person 1', 'One'), ('Person 2', 'Two'), ('Person 3', 'Three')], default='Person 1', max_length=50)),
                ('kids', models.CharField(choices=[('Kids 1', 'Kids 1'), ('Kids 2', 'Kids 2'), ('Kids 3', 'Kids 3')], default='Kids 1', max_length=128)),
                ('message', models.TextField()),
            ],
        ),
    ]
